@startuml
left to right direction

actor 利用者 as a
actor 看護師 as b

rectangle 診察予約システム{
    usecase 予約を登録する
    usecase 予約情報を確認する
    usecase 予約取り消しをする
    usecase 今の順番を閲覧する
}

    a --> 予約を登録する
    a --> 予約情報を確認する
    a --> 予約取り消しをする
    a --> 今の順番を閲覧する
    b --> 今の順番を閲覧する

@enduml