@startuml 演習３－５
object "Aさん:利用者クラス" as a{

}

object "Bさん:利用者クラス" as b{

}

object "301号室:部屋クラス" as c{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

object "302号室:部屋クラス" as d{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

object "303号室:部屋クラス" as e{
    部屋タイプ=Aクラス
    価格=11000円
    キャンペーン価格=9000円
}

a -- c
b -- e
@enduml