@startuml
left to right direction

[*] --> メニュー画面
メニュー画面 --> 今の順番: 今の順番ボタンを押す
今の順番 --> メニュー画面: メニューボタンを押す

あなたの順番 -right-> メニュー画面: メニューボタンを押す
予約と確認 --> あなたの順番: 登録ボタン押したとき
予約と確認 --> あなたの順番: 確認ボタン押したとき
予約と確認 --> メニュー画面: 削除ボタン押す
メニュー画面 --> 予約と確認: 名前と電話番号入力
メニュー画面 --left--> [*]

@enduml