@startuml 演習３－６
object "髙橋洋平さん:社員クラス" as 髙橋洋平{

}
object "樋口正之さん:社員クラス" as 樋口正之{
    
}
object "情報処理安全確保支援士:資格クラス" as 情報処理安全確保支援士{

}
object "LinuC試験Level1:資格クラス" as LinuC試験Level1{

}
髙橋洋平--情報処理安全確保支援士
髙橋洋平--LinuC試験Level1
樋口正之--情報処理安全確保支援士

@enduml