@startuml 例題3
left to right direction
actor 申請者 as user #DDDDDD;line:black;line.bold;
actor 承認者 as user2 #DDDDDD;line:black;line.bold;
actor 経理担当者 as user3 #DDDDDD;line:black;line.bold;
actor 交通費精算システム  as admin#DDDDDD;line:black;line.bold;
rectangle 出張申請システム {
usecase  出張申請を登録する as T
usecase 出張申請を提出する 
usecase 出張申請を承認する 
usecase 出張申請を却下する  
usecase 出張申請を差し戻す
usecase 出張申請を確認する
}
user --> T
user --> 出張申請を提出する
user2 --> 出張申請を承認する
user2 --> 出張申請を却下する
user2 --> 出張申請を差し戻す
user2 --> 出張申請を確認する
user3 --> 出張申請を確認する
T <-- admin
@enduml