@startuml ユースケース図
left to right direction
actor 利用者 as user #DDDDDD;line:black;line.bold;
actor 従業員 as user2 #DDDDDD;line:black;line.bold;
actor 管理者 as user3 #DDDDDD;line:black;line.bold;
rectangle ホテル予約システム {
usecase 会員登録する
usecase キャンペーン
usecase 空室状況閲覧する
usecase ログインする
usecase (<u>予約する</u>\n拡張点\nキャンペーン期間\n会員登録する) as input
usecase 予約集計する
usecase 空室状況入力する
user-[bold]->(会員登録する)
user-[bold]->(空室状況閲覧する)
user2-[bold]->(空室状況入力する)
user3-[bold]->(予約集計する)
}
(キャンペーン) ..> input : <<extend>>
(会員登録する) ..> input : <<extend>>
input ..> ログインする : <<include>>
予約集計する ..> ログインする : <<include>>
空室状況入力する ..> ログインする : <<include>>
user2 <|-- user3
@enduml